### ISSUE TITLE
Missing labels for certain SWT widgets

### ISSUE THREAD

**Issue by eum2o** [ustok/swtbot-spy#5]
Missing labels for:
- org.eclipse.swt.widgets.DateTime 
- org.eclipse.swt.widgets.ToolItem
- org.eclipse.swt.widgets.Spinner

(Ids are installed and can be used by SWTBot, but they're not shown when STRG+Q is pressed)

Please make SWTBotSpy to show IDs for mentioned widgets.

**Comment by ingomohr** [comment]
- problem was that Composites were skipped when creating spy-labels
- ToolItems are no Controls so they were ignored, as well. Added special handling for Toolbars to add spy-labels for their items.
  - The code is mostly duplicate, but it'll do for now. The whole UI is rather ugly, anyway. We should do a new and proper design.

tests:
- cleared up local repo and rebuilt: success
- created build 1.1.1.201301282125 and installed to acceptance-test-Eclipse
- ran manual acceptance test using (now improved) test view: ok
- deployed build to swtbot-spy release repo location. http://www.ustok.org/downloads/releases/repos/swtbot_spy/

fix notes:
- copy-on-doubleclick works (on MacOSX 10.8) only on Labels. We live with it for now.
